# 第4章 数据类型和结构

## 4.1 基本数据类型

### 4.1.1 整数

In [1]:
a = 10
type(a)  # int
# 调用 blt_length 方法， 获得表现 int 对象所需的位数
a.bit_length()  # 4
a = 100000
# 对象所赋的整数值越大， 需要的位数越多
a.bit_length()  # 17
googol = 10 ** 100
googol.bit_length()  # 333

333

### 4.1.2 浮点数

In [2]:
type(1 / 4)  # float
b = 0.35
type(b)  # float
b + 0.1  # 0.44999999999999996

0.44999999999999996

### 4.1.3 字符串

In [3]:
t = 'this is a string object'
t.capitalize()  # 'This is a string object'
t.split()  # ['this', 'is', 'a', 'string', 'object']
t.find('string')  # 10
t.find('Python')  # -1
t.replace(' ', '|')  # 'this|is|a|string|object'
'http://www.python.org'.strip('htp:/')  # 'www.python.org'

'www.python.org'

* 字符串方法

| 方法       | 参数                                    | 返回/结果                                       |
| ---------- | --------------------------------------- | ----------------------------------------------- |
| cpitalize  | ()                                      | 复制字符串，将第一个字符改成大写                |
| count      | sub[,star[,end]])                       | 计算子字符串出现的次数                          |
| decode     | [encoding[,errors]])                    | 用encoding指定的编码方式（例如UTF-8）解码字将串 |
| encode     | ([encoding[,errors]])                   | 字符串编码形式                                  |
| find       | (sub[,start[,end]])                     | 找到的子字符串（最低）索引                      |
| join       | (seq)                                   | 连接seq序列中的字符串                           |
| replace    | (old,new[,count]) 用new替换前count个old |                                                 |
| split      | ([sep[,maxsplit]])                      | 字符串中的单词列表，以sep作为分隔符             |
| splitlines | ([keepends])                            | 如果keepends为真,以行结束符/换行符分隔的行      |
| strip      | (chars)                                 | 从字符串首／尾删除chars中的字符                 |
| upper      | ()                                      | 复制字符串 ， 所有字母政为大写                  |

* 正则表达式

In [4]:
import re

series = """
'01/18/2014 13:00:00',100,'1st;
'01/18/2014 13:30:00',110,'snd;
'01/18/2014 14:00:00',120,'3rd;
"""
dt = re.compile("'[0-9/:\s]+'")  # 正则两边的单引号必须有，不然匹配的结果都散了
result = dt.findall(series)
# ["'01/18/2014 13:00:00'", "'01/18/2014 13:30:00'", "'01/18/2014 14:00:00'"]

from datetime import datetime

pydt = datetime.strptime(result[0].replace("'", ""), '%m/%d/%Y %H:%M:%S')
print(pydt)  # 2014-01-18 13:00:00

2014-01-18 13:00:00


## 4.2 基本数据结构

### 4.2.1 元组

In [5]:
t = (1, 2.5, 'data')
type(t)  # tuple
t = 1, 2.5, 'data'  # 可以去掉括号
type(t)  # tuple
# Python使用零起点编号，元组的第3个元素在索引位置2上
t[2]  # 'data'
type(t[2])  # str
t.count('data')  # 1
t.index('data')  # 2

2

### 4.2.2 列表

In [6]:
l = [1, 2.5, 'data']
l.append([4, 3])  # [1, 2.5, 'data', [4, 3]]
l.extend([4, 3])  # [1, 2.5, 'data', [4, 3], 4, 3]
l.insert(1, 'insert')  # [1, 'insert', 2.5, 'data', [4, 3], 4, 3]
l.append('data')  # [1, 'insert', 2.5, 'data', [4, 3], 4, 3, 'data']
l.remove('data')  # [1, 'insert', 2.5, [4, 3], 4, 3, 'data'] 移除了第一个匹配的，如果不存在会报错
p = l.pop(3)
print(l, p)  # [1, 'insert', 2.5, 4, 3, 'data'] [4, 3]
del l[0]  # ['insert', 2.5, 4, 3, 'data']

[1, 'insert', 2.5, 4, 3, 'data'] [4, 3]


* 切片操作

In [7]:
l = [1, 'insert', 2.5, 1.0, 1.5, 2.0]
l[2:5]  # 3rd to 5th elements ['data', [4, 3], 4]
# [2.5, 1.0, 1.5]

[2.5, 1.0, 1.5]

* 列表对象操作和方法

| 方法         | 参数                   | 返回/结果                             |
| ------------ | ---------------------- | ------------------------------------- |
| l[i]=x       | [i]                    | 用x代替第i个元素                      |
| l[i:j:k]=s   | [i:j:k]                | 用s代替从i到j-1号元素中的每第k个元素  |
| append       | (x)                    | 在对象后附加x                         |
| count        | (x)                    | 对象x出现的次数                       |
| del l[i:j:k] | [i:j:k]                | 删除索引值从i到j-1号元素的每第k个元素 |
| extend       | (s)                    | 将s的所有元素附加到对象               |
| index        | (x[,i[,j]])            | 元素i和j-1之间第一个x的索引           |
| insert       | (i,x)++                | 在索引i之前插入x                      |
| remove       | (i)                    | 删除索引为i的元素                     |
| pop          | (i)                    | 删除索引为i的元素并返回               |
| reverse      | ()                     | 颠倒所有项目的顺序                    |
| sort         | (cmp,[,key[,reverse]]) | 排序所有项目                          |

### 4.2.5 字典

In [8]:
d = {
    'Name': 'Angela Merkel',
    'Country': 'Germany',
    'Profession': 'Chancelor',
    'Age': 60
}
type(d)  # dict
print(d['Name'], d['Age'])  # Angela Merkel 60
d.items()
# dict_items([('Name', 'Angela Merkel'), ('Country', 'Germany'), ('Profession', 'Chancelor'), ('Age', 60)])
birthday = True
if birthday is True:
    d['Age'] += 1
print(d['Age'])  # 61

for item in d.items():
    print(item)
# ('Name', 'Angela Merkel')
# ('Country', 'Germany')
# ('Profession', 'Chancelor')
# ('Age', 61)

for value in d.values():
    print(type(value))
# <class 'str'>
# <class 'str'>
# <class 'str'>
# <class 'int'>

Angela Merkel 60
61
('Name', 'Angela Merkel')
('Country', 'Germany')
('Profession', 'Chancelor')
('Age', 61)
<class 'str'>
<class 'str'>
<class 'str'>
<class 'int'>


* 字典对象精选操作和方法

| 方法     | 参数  | 返回/结果                 |
| -------- | ----- | ------------------------- |
| d[k]     | [k]   | d中键码为k的项目          |
| d[k]=x   | [k]   | 将键码为k的项目设置为x    |
| del d[k] | [k]   | 删除键码为k的项目         |
| clear    | ()    | 删除所有项目              |
| copy     | ()    | 创建一个拷贝              |
| has_key  | (k)   | 如果k是一个键码，为真     |
| items    | ()    | 所有键-值对的拷贝         |
| keys     | ()    | 所有键码的拷贝            |
| popitem  | (k)   | 返回并删除键码为k的项目   |
| update   | ([e]) | 用来自e的项目更新字典项目 |
| values   | ()    | 所有值得拷贝              |

### 4.2.6 集合

In [9]:
s = set(['u', 'd', 'ud', 'du', 'd', 'du'])  # {'d', 'du', 'u', 'ud'}
t = set(['d', 'dd', 'uu', 'u'])
s.union(t)  # all of s and t {'d', 'dd', 'du', 'u', 'ud', 'uu'}
s.intersection(t)  # both in s and t  {'d', 'u'}
s.difference(t)  # in s but not t  {'du', 'ud'}
t.difference(s)  # {'dd', 'uu'}
s.symmetric_difference(t)  # in either one but not both  {'dd', 'du', 'ud', 'uu'}

from random import randint

l = [randint(0, 10) for i in range(1000)]
l[:20]  # [6, 5, 4, 10, 1, 1, 6, 0, 2, 0, 5, 3, 3, 4, 6, 7, 2, 0, 3, 2]
s = set(l)
s  # {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

## 4.3 NumPy数据结构

### 4.3.1 用 Pyhon 列表形成数组

In [10]:
v = [0.5, 0, 75, 1, 0, 1.5, 2.0]  # vector of numbers
m = [v, v, v]  # matrix of numbers
# [[0.5, 0, 75, 1, 0, 1.5, 2.0],
#  [0.5, 0, 75, 1, 0, 1.5, 2.0],
#  [0.5, 0, 75, 1, 0, 1.5, 2.0]]
m[1]  # [0.5, 0, 75, 1, 0, 1.5, 2.0]
m[1][0]  # 0.5

v1 = [0.5, 1.5]
v2 = [1, 2]
m = [v1, v2]  # [[0.5, 1.5], [1, 2]]
c = [m, m]  # cube of numbers  [[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]
c[1][1][0]  # 1

v = [0.5, 0, 75, 1, 0, 1.5, 2.0]  # vector of numbers
m = [v, v, v]  # matrix of numbers
# [[0.5, 0, 75, 1, 0, 1.5, 2.0],
#  [0.5, 0, 75, 1, 0, 1.5, 2.0],
#  [0.5, 0, 75, 1, 0, 1.5, 2.0]]
v[0] = 'Python'
m
# [['Python', 0, 75, 1, 0, 1.5, 2.0],
#  ['Python', 0, 75, 1, 0, 1.5, 2.0],
#  ['Python', 0, 75, 1, 0, 1.5, 2.0]]
# 使用copy模块的deepcopy函数可以避免这一现象
from copy import deepcopy

v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = 3 * [deepcopy(v)]
m
# [[0.5, 0.75, 1.0, 1.5, 2.0],
#  [0.5, 0.75, 1.0, 1.5, 2.0],
#  [0.5, 0.75, 1.0, 1.5, 2.0]]

v[0] = 'Python'
m
# [[0.5, 0.75, 1.0, 1.5, 2.0],
#  [0.5, 0.75, 1.0, 1.5, 2.0],
#  [0.5, 0.75, 1.0, 1.5, 2.0]]

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

### 4.3.2 常规NumPy数组

In [11]:
import numpy as np

a = np.array([0, 0.5, 1.0, 1.5, 2.0])
type(a)  # numpy.ndarray
a[:2]  # indexing as with list objects in 1 dimension
# array([ 0. ,  0.5])

a.sum()  # sum of all elements
# 5.0
a.std()  # standard deviation
# 0.70710678118654757
a.cumsum()  # running cumulative sum
# array([ e. , 0.5, 1.5, 3. , 5. ])
a * 2
# array([ 0.,  1.,  2.,  3.,  4.])
a ** 2
# array([ 0.  ,  0.25,  1.  ,  2.25,  4.  ])
np.sqrt(a)
# array([ 0.        ,  0.70710678,  1.        ,  1.22474487,  1.41421356])

b = np.array([a, a * 2])
# array([[ 0. ,  0.5,  1. ,  1.5,  2. ],
#        [ 0. ,  1. ,  2. ,  3. ,  4. ]])
b[0]
# array([ 0. ,  0.5,  1. ,  1.5,  2. ])

b[0, 2]  # third element of first row
# 1.0
b.sum()
# 15.0

b.sum(axis=0)
# sum along axis 0， i.e. column-wise sum
# array([ 0. ,  1.5,  3. ,  4.5,  6. ])

b.sum(axis=1)
# sum along axis 11 i.e. row-wise sum
# array([  5.,  10.])

c = np.zeros((2, 3, 4), dtype='i', order='C')
# array([[[0, 0, 0, 0],
#         [0, 0, 0, 0],
#         [0, 0, 0, 0]],
#        [[0, 0, 0, 0],
#         [0, 0, 0, 0],
#         [0, 0, 0, 0]]], dtype=int32)

d = np.ones_like(c, dtype='float16', order='C')
# array([[[ 1.,  1.,  1.,  1.],
#         [ 1.,  1.,  1.,  1.],
#         [ 1.,  1.,  1.,  1.]],
#        [[ 1.,  1.,  1.,  1.],
#         [ 1.,  1.,  1.,  1.],
#         [ 1.,  1.,  1.,  1.]]], dtype=float16)

### 4.3.3 结构数组

In [12]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'), ('Height', 'f'), ('Children/Pets', 'i4', 2)])
s = np.array([('Smith', 45, 1.83, (0, 1)),
              ('Jones', 53, 1.72, (2, 2))], dtype=dt)
s
# array([(b'Smith', 45,  1.83000004, [0, 1]),
#        (b'Jones', 53,  1.72000003, [2, 2])],
#       dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

s['Name']
# array([b'Smith', b'Jones'],
#       dtype='|S10')
s['Height'].mean()
# 1.7750001
s[1]['Age']
# 53

53

## 4.4 代码向量化

In [13]:
r = np.random.standard_normal((4, 3))
r
# array([[-0.86142195, -1.10576948, -1.72895607],
#        [-0.52694343,  0.885586  ,  2.09117311],
#        [ 1.17578779, -0.81735752, -0.79021266],
#        [-0.16469963,  2.31507942,  0.17910542]])

s = np.random.standard_normal((4, 3))
s
# array([[-0.40514995,  0.21406042, -0.89967644],
#        [ 1.98133139, -2.29530214,  0.23899185],
#        [-1.5984521 , -0.37488275,  1.52037602],
#        [ 0.53853487,  0.79409684, -1.07606899]])
r + s
# array([[-1.2665719 , -0.89170906, -2.62863251],
#        [ 1.45438796, -1.40971615,  2.33016495],
#        [-0.42266431, -1.19224027,  0.73016336],
#        [ 0.37383524,  3.10917626, -0.89696358]])

# NuinPy还支持所谓的广播
2 * r + 3
# array([[ 1.2771561 ,  0.78846104, -0.45791214],
#        [ 1.94611314,  4.77117199,  7.18234622],
#        [ 5.35157558,  1.36528496,  1.41957468],
#        [ 2.67060074,  7.63015885,  3.35821083]])
s=np.random.standard_normal(3)
# array([-0.97683636,  0.26286729, -1.17060774])
r
# array([[-0.86142195, -1.10576948, -1.72895607],
#        [-0.52694343,  0.885586  ,  2.09117311],
#        [ 1.17578779, -0.81735752, -0.79021266],
#        [-0.16469963,  2.31507942,  0.17910542]])
r + s
# array([[-0.86142195, -1.10576948, -1.72895607],
#        [-0.52694343,  0.885586  ,  2.09117311],
#        [ 1.17578779, -0.81735752, -0.79021266],
#        [-0.16469963,  2.31507942,  0.17910542]])
# r和s的第一行相加
r.transpose()  # 转置
# array([[-0.86142195, -0.52694343,  1.17578779, -0.16469963],
#        [-1.10576948,  0.885586  , -0.81735752,  2.31507942],
#        [-1.72895607,  2.09117311, -0.79021266,  0.17910542]])
np.shape(r.T)  # (3, 4)


def f(x):
    return 3 * x + 5

f(0.5)  # 6.5
f(r)
# array([[  2.41573416,   1.68269156,  -0.1868682 ],
#        [  3.41916971,   7.65675799,  11.27351933],
#        [  8.52736337,   2.54792744,   2.62936202],
#        [  4.50590111,  11.94523827,   5.53731625]])

array([[ 7.25790885,  2.37863844,  3.27296117],
       [-1.84499004,  4.24901217, -0.46981423],
       [ 5.93149192,  1.08950548,  2.63777532],
       [ 6.8162141 ,  3.73219093,  4.27919486]])

## 4.5 内存布局

In [14]:
x = np.random.standard_normal((5, 10000000))
y = 2 * x + 3
C = np.array((x, y), order='C') # 类 C 语言内存布局（行优先）
F = np.array((x, y), order='F') # 类 Fortran 内存布局（列优先）
x = 0.0
y = 0.0  # memory cleanup

%timeit C.sum()
# 1 loop, best of 3: 146 ms per loop

%timeit F.sum()
# 1 loop, best of 3: 145 ms per loop

%timeit C[0].sum(axis=0)  # 对每列元素求和
# 10 loops, best of 3: 130 ms per loop
%timeit C[0].sum(axis=1)  # 对每行元素求和
# 10 loops, best of 3: 73.5 ms per loop

52.6 ms ± 2.13 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
65.4 ms ± 9.92 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
85.4 ms ± 8.29 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
29.7 ms ± 3.32 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


> 行元素求和速度更快,这是因为每行元素都在相邻的存储位置上 